p1/main.out: p1/main.rs
	rustc p1/main.rs -o p1/main.out

A=""
run: p1/main.out 
	./p1/main.out $(A)

p2/main.out: p2/main.rs
	rustc p2/main.rs -o p2/main.out

run2: p2/main.out 
	./p2/main.out $(A)

